enum MISSION_STATES {
  PRE_FLIGHT = 'PRE_FLIGHT',
  FLIGHT = 'FLIGHT',
  POST_FLIGHT = 'POST_FLIGHT',
}

const MISSION_STATES_ARRAY = Object.values(MISSION_STATES)

export { MISSION_STATES, MISSION_STATES_ARRAY }
